name: chatbot
channels:
  - defaults
dependencies:
  - pip=25.3
  - python=3.13
  - numpy=2.4.1
  - pip:
      - tenacity==9.1.3
      - langchain==1.2.9 
      - openai==2.17.0
      - langchain-openai==1.1.7
      - neo4j==6.1.0
      - streamlit==1.54.0
      - langchainhub==0.1.21
      - langchain-neo4j==0.8.0
      - langchain_google_genai==4.2.0
